Repository AMReX-Astro/Microphysics, pull requests merged in 2024-07, with the labels that each got.

#1605 Updated primordial chemistry actual_rhs.H to replace std::pow with a combo of std::exp and std::log, added free-free cooling
  networks/primordial_chem/actual_rhs.H
Labels: enhancement

#1548 add SDC+NSE unit test example
  .github/workflows/nse_table.yml
  unit_test/burn_cell_sdc/burn_cell.H
  unit_test/burn_cell_sdc/ci-benchmarks/aprox19_NSE_state_over_time.txt
  unit_test/burn_cell_sdc/inputs_aprox19.nse.ci
Labels: test coverage, unit test, nse

#1547 add a second T check to tablular NSE
  nse_tabular/_parameters
  nse_tabular/nse_table_check.H
  sphinx_docs/source/nse.rst
  unit_test/burn_cell/ci-benchmarks/aprox19_nse_unit_test.out
Labels: nse

#1544 add NSE bailout to RKC
  integration/RKC/rkc.H
  integration/VODE/vode_type.H
  integration/integrator_data.H
Labels: nse

#1549 Remove strang nse
  .github/workflows/nse_table.yml
  Make.Microphysics_extern
  integration/Make.package
  integration/nse_update_strang.H
  unit_test/test_nse_interp/GNUmakefile
Labels: nse

#1628 more network documentation
  networks/ECSN/ecsn_network_generation.py
  sphinx_docs/source/CNO_He_burn.png
  sphinx_docs/source/ECSN.png
  sphinx_docs/source/cno_extras_hide_alpha.png
  sphinx_docs/source/networks.rst
  sphinx_docs/source/nova.png
  sphinx_docs/source/nova2.png
  sphinx_docs/source/subch_approx.png
  sphinx_docs/source/subch_full.png
Labels: documentation

#1631 remove "using namespace eos" from headers
  EOS/breakout/actual_eos.H
  EOS/gamma_law/actual_eos.H
  EOS/multigamma/actual_eos.H
  EOS/polytrope/actual_eos.H
  EOS/primordial_chem/actual_eos.H
  EOS/rad_power_law/actual_eos.H
  EOS/tillotson/actual_eos.H
Labels: cleaning
