Repository AMReX-Astro/Microphysics, pull requests merged in 2025-02, with the labels that each got.

#1735 more work on the docs intro
  Docs/source/burn_cell.rst
  Docs/source/getting_started.rst
  Docs/source/rp_intro.rst
Labels: documentation

#1737 document eos_cell.H
  Docs/source/burn_cell.rst
  Docs/source/eos_cell.rst
  Docs/source/one_zone_tests.rst
Labels: documentation

#1736 remove duplicate init_species_all_equal in favor of uniform_xn
  Docs/source/burn_cell.rst
  unit_test/_parameters
  unit_test/burn_cell/_parameters
  unit_test/burn_cell/burn_cell.H
  unit_test/burn_cell_sdc/burn_cell.H
  unit_test/eos_cell/eos_cell.H
  unit_test/jac_cell/jac_cell.H
  unit_test/react_util.H
  unit_test/test_react/_parameters
Labels: cleaning

#1738 clean-up and document jac_cell
  .github/workflows/jac_cell.yml
  Docs/source/eos_cell.rst
  Docs/source/jac_cell.rst
  Docs/source/one_zone_tests.rst
  Docs/source/refs.bib
  Docs/source/templated_networks.rst
  Docs/source/unit_tests.rst
  unit_test/jac_cell/README.md
  unit_test/jac_cell/_parameters
  unit_test/jac_cell/ci-benchmarks/jac_cell_aprox13.out
  unit_test/jac_cell/inputs
  unit_test/jac_cell/inputs_aprox13
  unit_test/jac_cell/jac_cell.H
Labels: documentation, cleaning

#1740 fix typo in sphinx .. index::
  Docs/source/eos_implementations.rst
Labels: documentation

#1739 show example output on the eos_cell docs page
  Docs/source/eos_cell.rst
Labels: documentation

#1741 split up the NSE docs into subpages
  Docs/source/nse.rst
  Docs/source/nse_net.rst
  Docs/source/nse_tabular.rst
Labels: documentation

#1744 some style fixes to design docs
  Docs/source/design.rst
Labels: documentation

#1745 namespace and clang-tidy changes
  Docs/source/integrators.rst
  Docs/source/templated_networks.rst
  Docs/source/transport.rst
  EOS/multigamma/eos_composition.H
  EOS/ztwd/actual_eos.H
  conductivity/stellar/actual_conductivity.H
  integration/nse_update_sdc.H
  integration/utils/nonaka_plot.H
  networks/aprox21/actual_network.H
  nse_solver/nse_eos.H
  opacity/breakout/actual_opacity.H
  opacity/opacity.H
  opacity/rad_power_law/actual_opacity.H
  unit_test/burn_cell/burn_cell.H
  unit_test/burn_cell_metal_chem/burn_cell.H
  unit_test/burn_cell_primordial_chem/burn_cell.H
  unit_test/burn_cell_sdc/burn_cell.H
  unit_test/eos_cell/eos_cell.H
  unit_test/jac_cell/jac_cell.H
  unit_test/nse_net_cell/_parameters
  unit_test/nse_net_cell/burn_cell.H
  unit_test/nse_net_cell/main.cpp
  unit_test/nse_net_cell/make_table/burn_cell.H
  unit_test/nse_net_cell/make_table/main.cpp
  unit_test/nse_table_cell/main.cpp
  unit_test/nse_table_cell/nse_cell.H
  unit_test/part_func_cell/_parameters
  unit_test/part_func_cell/main.cpp
  unit_test/part_func_cell/pf_cell.H
  unit_test/react_util.H
  unit_test/test_conductivity/conductivity_util.cpp
  unit_test/test_conductivity/main.cpp
  unit_test/test_jac/jac_zones.H
  unit_test/test_jac/main.cpp
  unit_test/test_neutrino_cooling/main.cpp
  unit_test/test_neutrino_cooling/neutrino_util.cpp
  unit_test/test_nse_interp/nse_cell.H
  unit_test/test_react/main.cpp
  unit_test/test_react/react_zones.H
  unit_test/test_rhs/main.cpp
  unit_test/test_rhs/rhs_zones.H
  unit_test/test_sdc/main.cpp
  unit_test/test_sdc/react_zones.H
  unit_test/test_sdc_vode_rhs/main.cpp
  unit_test/test_sdc_vode_rhs/vode_rhs_test.H
Labels: cleaning

#1750 update hip action -- ubuntu 20.04 runner is going away
  .github/workflows/dependencies/dependencies_hip.sh
  .github/workflows/hip.yml
Labels: github_actions

#1752 replace AMREX_PARALLEL_FOR_3D -> amrex::ParallelFor
  unit_test/test_aprox_rates/aprox_rates_util.cpp
  unit_test/test_conductivity/conductivity_util.cpp
  unit_test/test_eos/eos_util.cpp
  unit_test/test_jac/main.cpp
  unit_test/test_rhs/main.cpp
  unit_test/test_sdc/main.cpp
Labels: cleaning

#1753 remove make stuff for sparse jacobian
  Make.Microphysics
Labels: cleaning

#1751 add a doc section about GPUs
  Docs/source/design.rst
  Docs/source/unit_tests.rst
Labels: documentation

#1755 remove the CRSEGRNDOMP macro
  Make.Microphysics
Labels: cleaning

#1717 remove some old Fortran stuff from the build system
  Make.Microphysics
Labels: cleaning

#1754 remove openacc hooks in build system
  Make.Microphysics
Labels: cleaning

#1756 move the autodiff docs into the Util section
  Docs/source/index.rst
Labels: documentation

#1747 document burn_cell_sdc
  Docs/source/burn_cell.rst
  Docs/source/burn_cell_sdc.rst
  Docs/source/eos.rst
  Docs/source/one_zone_tests.rst
  Docs/source/unit_test_runtime_parameters.rst
  Docs/source/unit_tests.rst
  unit_test/burn_cell_sdc/parse_integration_failure.py
Labels: documentation

#1758 add refs to pynucastro
  Docs/source/networks.rst
  Docs/source/nse_tabular.rst
  Docs/source/refs.bib
Labels: documentation

#1759 fix some reference macros
  Docs/source/eos_implementations.rst
  Docs/source/networks.rst
  Docs/source/refs.bib
  Docs/source/screening.rst
Labels: documentation

#1766 docs: for he-burn-31anp and he-burn-36a add zoom plots of iron group
  Docs/source/networks.rst
  networks/he-burn/he-burn-31anp/he-burn-31anp-zoom.png
  networks/he-burn/he-burn-31anp/he-burn-31anp.png
  networks/he-burn/he-burn-31anp/he_burn_31anp.py
  networks/he-burn/he-burn-36a/he-burn-36a-zoom.png
  networks/he-burn/he-burn-36a/he_burn_36a.py
Labels: documentation

#1765 he-burn nets: also print out number of derived rates
  networks/he-burn/he-burn-31anp/he_burn_31anp.py
  networks/he-burn/he-burn-36a/he_burn_36a.py
Labels: reactions

#1767 fix link format in docs
  Docs/source/design.rst
Labels: documentation

#1760 Document the build system
  Docs/source/build_system.rst
  Docs/source/index.rst
  Docs/source/networks.rst
  Docs/source/screening.rst
  Docs/source/sdc.rst
Labels: documentation

#1746 Delete duplicated network nova2
  Docs/source/networks.rst
  Docs/source/nova.png
  Docs/source/nova2.png
  networks/general_null/nova.net
  networks/nova/Make.package
  networks/nova/actual_network.H
  networks/nova/actual_network_data.cpp
  networks/nova/actual_rhs.H
  networks/nova/inputs.burn_cell.VODE
  networks/nova/network_plot.py
  networks/nova/nova.png
  networks/nova/nova.py
  networks/nova/partition_functions.H
  networks/nova/partition_functions_data.cpp
  networks/nova/pynucastro.net
  networks/nova/reaclib_rates.H
  networks/nova2/Make.package
  networks/nova2/_parameters
  networks/nova2/actual_network.H
  networks/nova2/actual_network_data.cpp
  networks/nova2/actual_rhs.H
  networks/nova2/inputs.burn_cell.VODE
  networks/nova2/nova.png
  networks/nova2/nova2.py
  networks/nova2/partition_functions.H
  networks/nova2/reaclib_rates.H
  networks/nova2/table_rates.H
  networks/nova2/table_rates_data.cpp
  networks/nova2/tfactors.H
Labels: reactions, cleaning
